### ISSUE TITLE
[Process Failed] comes up everytime.

### ISSUE THREAD

**Issue by 0x14307** [UlyssesWu/ASNR#1]

**Comment by UlyssesWu** [comment]
Show me the full output, and provide a sample program if you can.
Otherwise you may have to fix it by yourself.

**Comment by 0x14307** [comment]
![Capture](https://user-images.githubusercontent.com/56172613/94310919-41296880-ff2f-11ea-919e-12ee8925e474.PNG)

**Comment by UlyssesWu** [comment]
I just fixed a bug. You can pull the latest commits and try again, and show me the full log if still failing.
Or, could you upload the program.exe or send it to my email?

**Comment by 0x14307** [comment]
I'll try it out.

**Comment by 0x14307** [comment]
Now says: "Could not load the target file: First parameter should be a valid path"
Also when tried with a different .exe file it gives the same "process failed" error.

**Comment by UlyssesWu** [comment]
"First parameter should be a valid path": maybe your target program's name contains spaces? If so, you should try something like `asnr.exe "test program.exe"`.

The updated code should print the detailed exception alongside with the process failed" error. Please show me the full log, or just upload the program you have tried.

**Comment by 0x14307** [comment]
[program.zip](https://github.com/UlyssesWu/ASNR/files/5321890/program.zip)

**Comment by UlyssesWu** [comment]
The program your provided is not strong named. Maybe you misunderstood this tool and you should find some tool you actually need.

**Comment by 0x14307** [comment]
Didn't know that! Thank you
